FROM maven:3.3.9-jdk-8-alpine as build-env
COPY ./spring-boot-redis/ /app/
WORKDIR /app
RUN mvn package -DskipTests

FROM gcr.io/distroless/java
WORKDIR /app
CMD ["app.jar"]
COPY --from=build-env /app/target/*.jar app.jar
